sudo: required
language: go

go:
- "1.12"

script:
- make dist

deploy:
  provider: releases
  api_key:
    secure: N1fs8i2TFUNe6gp5+lTyFIChIKkbQh4j5S2yOf6KZigyZcd09tCP02U7MdiQSyzkH0kd2o3i72S23/VgDeICFo8R2DWLU/FHI/caTJNF2C73VMKNn+8z/yejpuVLxRQhIYjiTlCaDNNRLuL047V8K9dEOFrXaD4cdOEXvXavhPg71Ez8SQ01nljrAptY9Jfl5AmYQ1PG311igjwrkcZEV4hYF7lp620G0UanErM+XPpD5xe8XzeJlatzkAwutG+EJCFjZqeK2A1kVGsEoD2muwBE8cvLQh7jPAbsWOboQKK5rcKpZkmld31cFQN1tnjDTBq0yyx14ZPDNKLG6iJvQMe6QdZ0IK+DAt7aLrBwNGSbigO5O7kpIbTykp4wvelOGwpPjnwC8cnGnCh59NGE11Jkj/u0bfzct171h9MDqS+0c+7Ds4wNLYK91fVSqpQM/fL7wwPtEPOWAedHnBO20sGy+PyzY8kHBm6mpNyIvegLQDgMNJVvJF5+4zuKDqsXti3sBP8ItpJRukuePUujCN3WVOB5owg693CXTmj2CvCRz7nuVP985sgEyx026bgKYGDjH9oqBAkRTAZrtf6Cwuzc1LkClhZB3okaapi6ts0AYNmRaPZoQ+Bs3rRDpXIqF5Jkt3ebr6tUiGRoVQC8SAeniZfJc0bV6Pzplilkmw0=
  file:
    - ./bin/faas-containerd
    - ./bin/faas-containerd-armhf
    - ./bin/faas-containerd-arm64
  skip_cleanup: true
  on:
    tags: true

env:
  - GO111MODULE=off
